Начало
htmlacademy-htmlcss/2259063-gllacy-36 pull request #1
Opened 2023-05-11 13:25 UTC by do6roetyro

2023-05-13 13:23 UTC, Kartaviy-arteom requested changes

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +              <svg class="navigation-logo" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg"
нкжно поправить форматирование фокумента

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +                <h3 class="catalog-tooltip-container-title visually-hidden">Каталог</h3>
выглядит избыточно

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +        <ul class="navigation-right-list">
это не совсем однородные элементы и список для них не очень подходит

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +                    <input class="search-input search-email" type="text" name="search" id="search"
описание поля

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +                      value="aaaaaa">
описание полей

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +                    <a class="login-tooltip-bottom-button pink-button" href="#">Войти</a>
это кнопка

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +                      <p class="cart-tooltip-description">310 ₽</p>
p здесь не очень подходит, лучше span тогда

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +                  <p class="cart-tooltip-result-description">Итого: 790 ₽</p>
так же p избыточно

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +                <ul class="cart-tooltip-list">
тут так же не все эти пункты можно поместить в список

2023-05-13 13:23 UTC, Kartaviy-arteom commented on index.html
> +          <h1 class="visually-hidden">Интернет-магазин мороженного "GllacyShop"</h1>
иерархия заголовков на странице

2023-05-17 16:53 UTC, Kartaviy-arteom requested changes

2023-05-17 16:53 UTC, Kartaviy-arteom commented on images/advantages_delivery.svg
лучше без окружности

2023-05-17 16:53 UTC, Kartaviy-arteom commented on styles/styles.css
> +  background-image: url(/images/advantages_icecream.svg);
это контентное изображение и кадрировать нужно на фронте

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +    <link rel="icon" type="image/png" href="images/favicon/favicon.png">
`<link rel="icon" type="image/png" sizes="32x32" href="images/favicon.png">`

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +              <p class="catalog-tooltip-field-title" href="#">Новинки</p>
невалидная разметка

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +                    <button class="login-tooltip-bottom-button pink-button" href="#">Войти</button>
href="#"

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +              <p class="catalog-tooltip-container-title visually-hidden">Каталог</p>
можно ссылкой или спаном

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +              <p class="catalog-tooltip-field-title" href="#">Новинки</p>
тут не p

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +          </div>
это нужно отформатировать

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +                    <input class="search-input search-email input-field" type="text" name="search" id="search"
required

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +                <form class="search-form" method="post" action="https://echo.htmlacademy.ru/"
подписи полей форм

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +                  <p class="cart-tooltip-container-title">Корзина</p>
это не параграф

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +                  <ul class="cart-tooltip-list">
тут список товаров можно

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +                  </svg><span class="visually-hidden">Youtube</span></a></li>
это ссылки на соцсети

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +              <p class="most-popular-products-name pistachio">Фисташка</p>
можно в принципе в article собрать, p тут плохо

2023-05-17 16:53 UTC, Kartaviy-arteom commented on index.html
> +                      aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg" width="15" height="14"
если не будет меняться, нужно в стили

2023-05-17 17:34 UTC, do6roetyro commented on index.html
> +              <p class="catalog-tooltip-container-title visually-hidden">Каталог</p>
уберу вообще

2023-05-17 17:35 UTC, do6roetyro commented on index.html
> +              <p class="catalog-tooltip-field-title" href="#">Новинки</p>
span

2023-05-17 17:36 UTC, do6roetyro commented on index.html
> +                  <p class="cart-tooltip-container-title">Корзина</p>
span

2023-05-17 17:37 UTC, do6roetyro commented on index.html
> +                  <ul class="cart-tooltip-list">
ОК

2023-05-17 17:37 UTC, do6roetyro commented on index.html
> +                  </svg><span class="visually-hidden">Youtube</span></a></li>
форматирование

2023-05-31 17:08 UTC, merged